<?php

/**
 * Flexv2sessionsFieldsPaymentInformationCard
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
namespace Pymt_Vas\Dependencies\CyberSource\Model;

use ArrayAccess;
/**
 * Flexv2sessionsFieldsPaymentInformationCard Class Doc Comment
 *
 * @category    Class
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Flexv2sessionsFieldsPaymentInformationCard implements ArrayAccess
{
    const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     * @var string
     */
    protected static $swaggerModelName = 'flexv2sessions_fields_paymentInformation_card';
    /**
     * Array of property to type mappings. Used for (de)serialization
     * @var string[]
     */
    protected static $swaggerTypes = ['number' => '\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount', 'type' => '\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount', 'securityCode' => '\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount', 'expirationMonth' => '\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount', 'expirationYear' => '\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount'];
    /**
     * Array of property to format mappings. Used for (de)serialization
     * @var string[]
     */
    protected static $swaggerFormats = ['number' => null, 'type' => null, 'securityCode' => null, 'expirationMonth' => null, 'expirationYear' => null];
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }
    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = ['number' => 'number', 'type' => 'type', 'securityCode' => 'securityCode', 'expirationMonth' => 'expirationMonth', 'expirationYear' => 'expirationYear'];
    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = ['number' => 'setNumber', 'type' => 'setType', 'securityCode' => 'setSecurityCode', 'expirationMonth' => 'setExpirationMonth', 'expirationYear' => 'setExpirationYear'];
    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = ['number' => 'getNumber', 'type' => 'getType', 'securityCode' => 'getSecurityCode', 'expirationMonth' => 'getExpirationMonth', 'expirationYear' => 'getExpirationYear'];
    public static function attributeMap()
    {
        return self::$attributeMap;
    }
    public static function setters()
    {
        return self::$setters;
    }
    public static function getters()
    {
        return self::$getters;
    }
    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];
    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['number'] = isset($data['number']) ? $data['number'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['securityCode'] = isset($data['securityCode']) ? $data['securityCode'] : null;
        $this->container['expirationMonth'] = isset($data['expirationMonth']) ? $data['expirationMonth'] : null;
        $this->container['expirationYear'] = isset($data['expirationYear']) ? $data['expirationYear'] : null;
    }
    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        return $invalid_properties;
    }
    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return true;
    }
    /**
     * Gets number
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount
     */
    public function getNumber()
    {
        return $this->container['number'];
    }
    /**
     * Sets number
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount $number
     * @return $this
     */
    public function setNumber($number)
    {
        $this->container['number'] = $number;
        return $this;
    }
    /**
     * Gets type
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount
     */
    public function getType()
    {
        return $this->container['type'];
    }
    /**
     * Sets type
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount $type
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;
        return $this;
    }
    /**
     * Gets securityCode
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount
     */
    public function getSecurityCode()
    {
        return $this->container['securityCode'];
    }
    /**
     * Sets securityCode
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount $securityCode
     * @return $this
     */
    public function setSecurityCode($securityCode)
    {
        $this->container['securityCode'] = $securityCode;
        return $this;
    }
    /**
     * Gets expirationMonth
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount
     */
    public function getExpirationMonth()
    {
        return $this->container['expirationMonth'];
    }
    /**
     * Sets expirationMonth
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount $expirationMonth
     * @return $this
     */
    public function setExpirationMonth($expirationMonth)
    {
        $this->container['expirationMonth'] = $expirationMonth;
        return $this;
    }
    /**
     * Gets expirationYear
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount
     */
    public function getExpirationYear()
    {
        return $this->container['expirationYear'];
    }
    /**
     * Sets expirationYear
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Flexv2sessionsFieldsOrderInformationAmountDetailsTotalAmount $expirationYear
     * @return $this
     */
    public function setExpirationYear($expirationYear)
    {
        $this->container['expirationYear'] = $expirationYear;
        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }
    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }
    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            // use JSON pretty print
            return json_encode(\Pymt_Vas\Dependencies\CyberSource\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }
        return json_encode(\Pymt_Vas\Dependencies\CyberSource\ObjectSerializer::sanitizeForSerialization($this));
    }
}