<?php

/**
 * PaymentsProducts
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
namespace Pymt_Vas\Dependencies\CyberSource\Model;

use ArrayAccess;
/**
 * PaymentsProducts Class Doc Comment
 *
 * @category    Class
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentsProducts implements ArrayAccess
{
    const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     * @var string
     */
    protected static $swaggerModelName = 'paymentsProducts';
    /**
     * Array of property to type mappings. Used for (de)serialization
     * @var string[]
     */
    protected static $swaggerTypes = ['cardProcessing' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsCardProcessing', 'alternativePaymentMethods' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsAlternativePaymentMethods', 'cardPresentConnect' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsCardPresentConnect', 'cybsReadyTerminal' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsCybsReadyTerminal', 'eCheck' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsECheck', 'payerAuthentication' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsPayerAuthentication', 'digitalPayments' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsDigitalPayments', 'secureAcceptance' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsSecureAcceptance', 'virtualTerminal' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsVirtualTerminal', 'currencyConversion' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsCurrencyConversion', 'tax' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax', 'customerInvoicing' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax', 'recurringBilling' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax', 'paymentOrchestration' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax', 'payouts' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsPayouts', 'differentialFee' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsDifferentialFee', 'payByLink' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax', 'unifiedCheckout' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsUnifiedCheckout', 'receivablesManager' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax', 'serviceFee' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsServiceFee', 'batchUpload' => '\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax'];
    /**
     * Array of property to format mappings. Used for (de)serialization
     * @var string[]
     */
    protected static $swaggerFormats = ['cardProcessing' => null, 'alternativePaymentMethods' => null, 'cardPresentConnect' => null, 'cybsReadyTerminal' => null, 'eCheck' => null, 'payerAuthentication' => null, 'digitalPayments' => null, 'secureAcceptance' => null, 'virtualTerminal' => null, 'currencyConversion' => null, 'tax' => null, 'customerInvoicing' => null, 'recurringBilling' => null, 'paymentOrchestration' => null, 'payouts' => null, 'differentialFee' => null, 'payByLink' => null, 'unifiedCheckout' => null, 'receivablesManager' => null, 'serviceFee' => null, 'batchUpload' => null];
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }
    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = ['cardProcessing' => 'cardProcessing', 'alternativePaymentMethods' => 'alternativePaymentMethods', 'cardPresentConnect' => 'cardPresentConnect', 'cybsReadyTerminal' => 'cybsReadyTerminal', 'eCheck' => 'eCheck', 'payerAuthentication' => 'payerAuthentication', 'digitalPayments' => 'digitalPayments', 'secureAcceptance' => 'secureAcceptance', 'virtualTerminal' => 'virtualTerminal', 'currencyConversion' => 'currencyConversion', 'tax' => 'tax', 'customerInvoicing' => 'customerInvoicing', 'recurringBilling' => 'recurringBilling', 'paymentOrchestration' => 'paymentOrchestration', 'payouts' => 'payouts', 'differentialFee' => 'differentialFee', 'payByLink' => 'payByLink', 'unifiedCheckout' => 'unifiedCheckout', 'receivablesManager' => 'receivablesManager', 'serviceFee' => 'serviceFee', 'batchUpload' => 'batchUpload'];
    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = ['cardProcessing' => 'setCardProcessing', 'alternativePaymentMethods' => 'setAlternativePaymentMethods', 'cardPresentConnect' => 'setCardPresentConnect', 'cybsReadyTerminal' => 'setCybsReadyTerminal', 'eCheck' => 'setECheck', 'payerAuthentication' => 'setPayerAuthentication', 'digitalPayments' => 'setDigitalPayments', 'secureAcceptance' => 'setSecureAcceptance', 'virtualTerminal' => 'setVirtualTerminal', 'currencyConversion' => 'setCurrencyConversion', 'tax' => 'setTax', 'customerInvoicing' => 'setCustomerInvoicing', 'recurringBilling' => 'setRecurringBilling', 'paymentOrchestration' => 'setPaymentOrchestration', 'payouts' => 'setPayouts', 'differentialFee' => 'setDifferentialFee', 'payByLink' => 'setPayByLink', 'unifiedCheckout' => 'setUnifiedCheckout', 'receivablesManager' => 'setReceivablesManager', 'serviceFee' => 'setServiceFee', 'batchUpload' => 'setBatchUpload'];
    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = ['cardProcessing' => 'getCardProcessing', 'alternativePaymentMethods' => 'getAlternativePaymentMethods', 'cardPresentConnect' => 'getCardPresentConnect', 'cybsReadyTerminal' => 'getCybsReadyTerminal', 'eCheck' => 'getECheck', 'payerAuthentication' => 'getPayerAuthentication', 'digitalPayments' => 'getDigitalPayments', 'secureAcceptance' => 'getSecureAcceptance', 'virtualTerminal' => 'getVirtualTerminal', 'currencyConversion' => 'getCurrencyConversion', 'tax' => 'getTax', 'customerInvoicing' => 'getCustomerInvoicing', 'recurringBilling' => 'getRecurringBilling', 'paymentOrchestration' => 'getPaymentOrchestration', 'payouts' => 'getPayouts', 'differentialFee' => 'getDifferentialFee', 'payByLink' => 'getPayByLink', 'unifiedCheckout' => 'getUnifiedCheckout', 'receivablesManager' => 'getReceivablesManager', 'serviceFee' => 'getServiceFee', 'batchUpload' => 'getBatchUpload'];
    public static function attributeMap()
    {
        return self::$attributeMap;
    }
    public static function setters()
    {
        return self::$setters;
    }
    public static function getters()
    {
        return self::$getters;
    }
    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];
    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['cardProcessing'] = isset($data['cardProcessing']) ? $data['cardProcessing'] : null;
        $this->container['alternativePaymentMethods'] = isset($data['alternativePaymentMethods']) ? $data['alternativePaymentMethods'] : null;
        $this->container['cardPresentConnect'] = isset($data['cardPresentConnect']) ? $data['cardPresentConnect'] : null;
        $this->container['cybsReadyTerminal'] = isset($data['cybsReadyTerminal']) ? $data['cybsReadyTerminal'] : null;
        $this->container['eCheck'] = isset($data['eCheck']) ? $data['eCheck'] : null;
        $this->container['payerAuthentication'] = isset($data['payerAuthentication']) ? $data['payerAuthentication'] : null;
        $this->container['digitalPayments'] = isset($data['digitalPayments']) ? $data['digitalPayments'] : null;
        $this->container['secureAcceptance'] = isset($data['secureAcceptance']) ? $data['secureAcceptance'] : null;
        $this->container['virtualTerminal'] = isset($data['virtualTerminal']) ? $data['virtualTerminal'] : null;
        $this->container['currencyConversion'] = isset($data['currencyConversion']) ? $data['currencyConversion'] : null;
        $this->container['tax'] = isset($data['tax']) ? $data['tax'] : null;
        $this->container['customerInvoicing'] = isset($data['customerInvoicing']) ? $data['customerInvoicing'] : null;
        $this->container['recurringBilling'] = isset($data['recurringBilling']) ? $data['recurringBilling'] : null;
        $this->container['paymentOrchestration'] = isset($data['paymentOrchestration']) ? $data['paymentOrchestration'] : null;
        $this->container['payouts'] = isset($data['payouts']) ? $data['payouts'] : null;
        $this->container['differentialFee'] = isset($data['differentialFee']) ? $data['differentialFee'] : null;
        $this->container['payByLink'] = isset($data['payByLink']) ? $data['payByLink'] : null;
        $this->container['unifiedCheckout'] = isset($data['unifiedCheckout']) ? $data['unifiedCheckout'] : null;
        $this->container['receivablesManager'] = isset($data['receivablesManager']) ? $data['receivablesManager'] : null;
        $this->container['serviceFee'] = isset($data['serviceFee']) ? $data['serviceFee'] : null;
        $this->container['batchUpload'] = isset($data['batchUpload']) ? $data['batchUpload'] : null;
    }
    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        return $invalid_properties;
    }
    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return true;
    }
    /**
     * Gets cardProcessing
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsCardProcessing
     */
    public function getCardProcessing()
    {
        return $this->container['cardProcessing'];
    }
    /**
     * Sets cardProcessing
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsCardProcessing $cardProcessing
     * @return $this
     */
    public function setCardProcessing($cardProcessing)
    {
        $this->container['cardProcessing'] = $cardProcessing;
        return $this;
    }
    /**
     * Gets alternativePaymentMethods
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsAlternativePaymentMethods
     */
    public function getAlternativePaymentMethods()
    {
        return $this->container['alternativePaymentMethods'];
    }
    /**
     * Sets alternativePaymentMethods
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsAlternativePaymentMethods $alternativePaymentMethods
     * @return $this
     */
    public function setAlternativePaymentMethods($alternativePaymentMethods)
    {
        $this->container['alternativePaymentMethods'] = $alternativePaymentMethods;
        return $this;
    }
    /**
     * Gets cardPresentConnect
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsCardPresentConnect
     */
    public function getCardPresentConnect()
    {
        return $this->container['cardPresentConnect'];
    }
    /**
     * Sets cardPresentConnect
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsCardPresentConnect $cardPresentConnect
     * @return $this
     */
    public function setCardPresentConnect($cardPresentConnect)
    {
        $this->container['cardPresentConnect'] = $cardPresentConnect;
        return $this;
    }
    /**
     * Gets cybsReadyTerminal
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsCybsReadyTerminal
     */
    public function getCybsReadyTerminal()
    {
        return $this->container['cybsReadyTerminal'];
    }
    /**
     * Sets cybsReadyTerminal
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsCybsReadyTerminal $cybsReadyTerminal
     * @return $this
     */
    public function setCybsReadyTerminal($cybsReadyTerminal)
    {
        $this->container['cybsReadyTerminal'] = $cybsReadyTerminal;
        return $this;
    }
    /**
     * Gets eCheck
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsECheck
     */
    public function getECheck()
    {
        return $this->container['eCheck'];
    }
    /**
     * Sets eCheck
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsECheck $eCheck
     * @return $this
     */
    public function setECheck($eCheck)
    {
        $this->container['eCheck'] = $eCheck;
        return $this;
    }
    /**
     * Gets payerAuthentication
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsPayerAuthentication
     */
    public function getPayerAuthentication()
    {
        return $this->container['payerAuthentication'];
    }
    /**
     * Sets payerAuthentication
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsPayerAuthentication $payerAuthentication
     * @return $this
     */
    public function setPayerAuthentication($payerAuthentication)
    {
        $this->container['payerAuthentication'] = $payerAuthentication;
        return $this;
    }
    /**
     * Gets digitalPayments
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsDigitalPayments
     */
    public function getDigitalPayments()
    {
        return $this->container['digitalPayments'];
    }
    /**
     * Sets digitalPayments
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsDigitalPayments $digitalPayments
     * @return $this
     */
    public function setDigitalPayments($digitalPayments)
    {
        $this->container['digitalPayments'] = $digitalPayments;
        return $this;
    }
    /**
     * Gets secureAcceptance
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsSecureAcceptance
     */
    public function getSecureAcceptance()
    {
        return $this->container['secureAcceptance'];
    }
    /**
     * Sets secureAcceptance
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsSecureAcceptance $secureAcceptance
     * @return $this
     */
    public function setSecureAcceptance($secureAcceptance)
    {
        $this->container['secureAcceptance'] = $secureAcceptance;
        return $this;
    }
    /**
     * Gets virtualTerminal
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsVirtualTerminal
     */
    public function getVirtualTerminal()
    {
        return $this->container['virtualTerminal'];
    }
    /**
     * Sets virtualTerminal
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsVirtualTerminal $virtualTerminal
     * @return $this
     */
    public function setVirtualTerminal($virtualTerminal)
    {
        $this->container['virtualTerminal'] = $virtualTerminal;
        return $this;
    }
    /**
     * Gets currencyConversion
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsCurrencyConversion
     */
    public function getCurrencyConversion()
    {
        return $this->container['currencyConversion'];
    }
    /**
     * Sets currencyConversion
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsCurrencyConversion $currencyConversion
     * @return $this
     */
    public function setCurrencyConversion($currencyConversion)
    {
        $this->container['currencyConversion'] = $currencyConversion;
        return $this;
    }
    /**
     * Gets tax
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax
     */
    public function getTax()
    {
        return $this->container['tax'];
    }
    /**
     * Sets tax
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax $tax
     * @return $this
     */
    public function setTax($tax)
    {
        $this->container['tax'] = $tax;
        return $this;
    }
    /**
     * Gets customerInvoicing
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax
     */
    public function getCustomerInvoicing()
    {
        return $this->container['customerInvoicing'];
    }
    /**
     * Sets customerInvoicing
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax $customerInvoicing
     * @return $this
     */
    public function setCustomerInvoicing($customerInvoicing)
    {
        $this->container['customerInvoicing'] = $customerInvoicing;
        return $this;
    }
    /**
     * Gets recurringBilling
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax
     */
    public function getRecurringBilling()
    {
        return $this->container['recurringBilling'];
    }
    /**
     * Sets recurringBilling
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax $recurringBilling
     * @return $this
     */
    public function setRecurringBilling($recurringBilling)
    {
        $this->container['recurringBilling'] = $recurringBilling;
        return $this;
    }
    /**
     * Gets paymentOrchestration
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax
     */
    public function getPaymentOrchestration()
    {
        return $this->container['paymentOrchestration'];
    }
    /**
     * Sets paymentOrchestration
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax $paymentOrchestration
     * @return $this
     */
    public function setPaymentOrchestration($paymentOrchestration)
    {
        $this->container['paymentOrchestration'] = $paymentOrchestration;
        return $this;
    }
    /**
     * Gets payouts
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsPayouts
     */
    public function getPayouts()
    {
        return $this->container['payouts'];
    }
    /**
     * Sets payouts
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsPayouts $payouts
     * @return $this
     */
    public function setPayouts($payouts)
    {
        $this->container['payouts'] = $payouts;
        return $this;
    }
    /**
     * Gets differentialFee
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsDifferentialFee
     */
    public function getDifferentialFee()
    {
        return $this->container['differentialFee'];
    }
    /**
     * Sets differentialFee
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsDifferentialFee $differentialFee
     * @return $this
     */
    public function setDifferentialFee($differentialFee)
    {
        $this->container['differentialFee'] = $differentialFee;
        return $this;
    }
    /**
     * Gets payByLink
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax
     */
    public function getPayByLink()
    {
        return $this->container['payByLink'];
    }
    /**
     * Sets payByLink
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax $payByLink
     * @return $this
     */
    public function setPayByLink($payByLink)
    {
        $this->container['payByLink'] = $payByLink;
        return $this;
    }
    /**
     * Gets unifiedCheckout
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsUnifiedCheckout
     */
    public function getUnifiedCheckout()
    {
        return $this->container['unifiedCheckout'];
    }
    /**
     * Sets unifiedCheckout
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsUnifiedCheckout $unifiedCheckout
     * @return $this
     */
    public function setUnifiedCheckout($unifiedCheckout)
    {
        $this->container['unifiedCheckout'] = $unifiedCheckout;
        return $this;
    }
    /**
     * Gets receivablesManager
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax
     */
    public function getReceivablesManager()
    {
        return $this->container['receivablesManager'];
    }
    /**
     * Sets receivablesManager
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax $receivablesManager
     * @return $this
     */
    public function setReceivablesManager($receivablesManager)
    {
        $this->container['receivablesManager'] = $receivablesManager;
        return $this;
    }
    /**
     * Gets serviceFee
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsServiceFee
     */
    public function getServiceFee()
    {
        return $this->container['serviceFee'];
    }
    /**
     * Sets serviceFee
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsServiceFee $serviceFee
     * @return $this
     */
    public function setServiceFee($serviceFee)
    {
        $this->container['serviceFee'] = $serviceFee;
        return $this;
    }
    /**
     * Gets batchUpload
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax
     */
    public function getBatchUpload()
    {
        return $this->container['batchUpload'];
    }
    /**
     * Sets batchUpload
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PaymentsProductsTax $batchUpload
     * @return $this
     */
    public function setBatchUpload($batchUpload)
    {
        $this->container['batchUpload'] = $batchUpload;
        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }
    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }
    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            // use JSON pretty print
            return json_encode(\Pymt_Vas\Dependencies\CyberSource\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }
        return json_encode(\Pymt_Vas\Dependencies\CyberSource\ObjectSerializer::sanitizeForSerialization($this));
    }
}