<?php

/**
 * Ucv1sessionsData
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
namespace Pymt_Vas\Dependencies\CyberSource\Model;

use ArrayAccess;
/**
 * Ucv1sessionsData Class Doc Comment
 *
 * @category    Class
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ucv1sessionsData implements ArrayAccess
{
    const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     * @var string
     */
    protected static $swaggerModelName = 'ucv1sessions_data';
    /**
     * Array of property to type mappings. Used for (de)serialization
     * @var string[]
     */
    protected static $swaggerTypes = ['orderInformation' => '\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataOrderInformation', 'buyerInformation' => '\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataBuyerInformation', 'clientReferenceInformation' => '\Pymt_Vas\Dependencies\CyberSource\Model\Upv1capturecontextsDataClientReferenceInformation', 'consumerAuthenticationInformation' => '\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataConsumerAuthenticationInformation', 'merchantInformation' => '\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataMerchantInformation', 'processingInformation' => '\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataProcessingInformation', 'recipientInformation' => '\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataRecipientInformation', 'merchantDefinedInformation' => '\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataMerchantDefinedInformation[]', 'deviceInformation' => '\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataDeviceInformation', 'paymentInformation' => '\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataPaymentInformation'];
    /**
     * Array of property to format mappings. Used for (de)serialization
     * @var string[]
     */
    protected static $swaggerFormats = ['orderInformation' => null, 'buyerInformation' => null, 'clientReferenceInformation' => null, 'consumerAuthenticationInformation' => null, 'merchantInformation' => null, 'processingInformation' => null, 'recipientInformation' => null, 'merchantDefinedInformation' => null, 'deviceInformation' => null, 'paymentInformation' => null];
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }
    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = ['orderInformation' => 'orderInformation', 'buyerInformation' => 'buyerInformation', 'clientReferenceInformation' => 'clientReferenceInformation', 'consumerAuthenticationInformation' => 'consumerAuthenticationInformation', 'merchantInformation' => 'merchantInformation', 'processingInformation' => 'processingInformation', 'recipientInformation' => 'recipientInformation', 'merchantDefinedInformation' => 'merchantDefinedInformation', 'deviceInformation' => 'deviceInformation', 'paymentInformation' => 'paymentInformation'];
    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = ['orderInformation' => 'setOrderInformation', 'buyerInformation' => 'setBuyerInformation', 'clientReferenceInformation' => 'setClientReferenceInformation', 'consumerAuthenticationInformation' => 'setConsumerAuthenticationInformation', 'merchantInformation' => 'setMerchantInformation', 'processingInformation' => 'setProcessingInformation', 'recipientInformation' => 'setRecipientInformation', 'merchantDefinedInformation' => 'setMerchantDefinedInformation', 'deviceInformation' => 'setDeviceInformation', 'paymentInformation' => 'setPaymentInformation'];
    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = ['orderInformation' => 'getOrderInformation', 'buyerInformation' => 'getBuyerInformation', 'clientReferenceInformation' => 'getClientReferenceInformation', 'consumerAuthenticationInformation' => 'getConsumerAuthenticationInformation', 'merchantInformation' => 'getMerchantInformation', 'processingInformation' => 'getProcessingInformation', 'recipientInformation' => 'getRecipientInformation', 'merchantDefinedInformation' => 'getMerchantDefinedInformation', 'deviceInformation' => 'getDeviceInformation', 'paymentInformation' => 'getPaymentInformation'];
    public static function attributeMap()
    {
        return self::$attributeMap;
    }
    public static function setters()
    {
        return self::$setters;
    }
    public static function getters()
    {
        return self::$getters;
    }
    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];
    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['orderInformation'] = isset($data['orderInformation']) ? $data['orderInformation'] : null;
        $this->container['buyerInformation'] = isset($data['buyerInformation']) ? $data['buyerInformation'] : null;
        $this->container['clientReferenceInformation'] = isset($data['clientReferenceInformation']) ? $data['clientReferenceInformation'] : null;
        $this->container['consumerAuthenticationInformation'] = isset($data['consumerAuthenticationInformation']) ? $data['consumerAuthenticationInformation'] : null;
        $this->container['merchantInformation'] = isset($data['merchantInformation']) ? $data['merchantInformation'] : null;
        $this->container['processingInformation'] = isset($data['processingInformation']) ? $data['processingInformation'] : null;
        $this->container['recipientInformation'] = isset($data['recipientInformation']) ? $data['recipientInformation'] : null;
        $this->container['merchantDefinedInformation'] = isset($data['merchantDefinedInformation']) ? $data['merchantDefinedInformation'] : null;
        $this->container['deviceInformation'] = isset($data['deviceInformation']) ? $data['deviceInformation'] : null;
        $this->container['paymentInformation'] = isset($data['paymentInformation']) ? $data['paymentInformation'] : null;
    }
    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        return $invalid_properties;
    }
    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return true;
    }
    /**
     * Gets orderInformation
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataOrderInformation
     */
    public function getOrderInformation()
    {
        return $this->container['orderInformation'];
    }
    /**
     * Sets orderInformation
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataOrderInformation $orderInformation
     * @return $this
     */
    public function setOrderInformation($orderInformation)
    {
        $this->container['orderInformation'] = $orderInformation;
        return $this;
    }
    /**
     * Gets buyerInformation
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataBuyerInformation
     */
    public function getBuyerInformation()
    {
        return $this->container['buyerInformation'];
    }
    /**
     * Sets buyerInformation
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataBuyerInformation $buyerInformation
     * @return $this
     */
    public function setBuyerInformation($buyerInformation)
    {
        $this->container['buyerInformation'] = $buyerInformation;
        return $this;
    }
    /**
     * Gets clientReferenceInformation
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Upv1capturecontextsDataClientReferenceInformation
     */
    public function getClientReferenceInformation()
    {
        return $this->container['clientReferenceInformation'];
    }
    /**
     * Sets clientReferenceInformation
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Upv1capturecontextsDataClientReferenceInformation $clientReferenceInformation
     * @return $this
     */
    public function setClientReferenceInformation($clientReferenceInformation)
    {
        $this->container['clientReferenceInformation'] = $clientReferenceInformation;
        return $this;
    }
    /**
     * Gets consumerAuthenticationInformation
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataConsumerAuthenticationInformation
     */
    public function getConsumerAuthenticationInformation()
    {
        return $this->container['consumerAuthenticationInformation'];
    }
    /**
     * Sets consumerAuthenticationInformation
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataConsumerAuthenticationInformation $consumerAuthenticationInformation
     * @return $this
     */
    public function setConsumerAuthenticationInformation($consumerAuthenticationInformation)
    {
        $this->container['consumerAuthenticationInformation'] = $consumerAuthenticationInformation;
        return $this;
    }
    /**
     * Gets merchantInformation
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataMerchantInformation
     */
    public function getMerchantInformation()
    {
        return $this->container['merchantInformation'];
    }
    /**
     * Sets merchantInformation
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataMerchantInformation $merchantInformation
     * @return $this
     */
    public function setMerchantInformation($merchantInformation)
    {
        $this->container['merchantInformation'] = $merchantInformation;
        return $this;
    }
    /**
     * Gets processingInformation
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataProcessingInformation
     */
    public function getProcessingInformation()
    {
        return $this->container['processingInformation'];
    }
    /**
     * Sets processingInformation
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataProcessingInformation $processingInformation
     * @return $this
     */
    public function setProcessingInformation($processingInformation)
    {
        $this->container['processingInformation'] = $processingInformation;
        return $this;
    }
    /**
     * Gets recipientInformation
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataRecipientInformation
     */
    public function getRecipientInformation()
    {
        return $this->container['recipientInformation'];
    }
    /**
     * Sets recipientInformation
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataRecipientInformation $recipientInformation
     * @return $this
     */
    public function setRecipientInformation($recipientInformation)
    {
        $this->container['recipientInformation'] = $recipientInformation;
        return $this;
    }
    /**
     * Gets merchantDefinedInformation
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataMerchantDefinedInformation[]
     */
    public function getMerchantDefinedInformation()
    {
        return $this->container['merchantDefinedInformation'];
    }
    /**
     * Sets merchantDefinedInformation
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataMerchantDefinedInformation[] $merchantDefinedInformation
     * @return $this
     */
    public function setMerchantDefinedInformation($merchantDefinedInformation)
    {
        $this->container['merchantDefinedInformation'] = $merchantDefinedInformation;
        return $this;
    }
    /**
     * Gets deviceInformation
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataDeviceInformation
     */
    public function getDeviceInformation()
    {
        return $this->container['deviceInformation'];
    }
    /**
     * Sets deviceInformation
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataDeviceInformation $deviceInformation
     * @return $this
     */
    public function setDeviceInformation($deviceInformation)
    {
        $this->container['deviceInformation'] = $deviceInformation;
        return $this;
    }
    /**
     * Gets paymentInformation
     * @return \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataPaymentInformation
     */
    public function getPaymentInformation()
    {
        return $this->container['paymentInformation'];
    }
    /**
     * Sets paymentInformation
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\Ucv1sessionsDataPaymentInformation $paymentInformation
     * @return $this
     */
    public function setPaymentInformation($paymentInformation)
    {
        $this->container['paymentInformation'] = $paymentInformation;
        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }
    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }
    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            // use JSON pretty print
            return json_encode(\Pymt_Vas\Dependencies\CyberSource\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }
        return json_encode(\Pymt_Vas\Dependencies\CyberSource\ObjectSerializer::sanitizeForSerialization($this));
    }
}