<?php

declare (strict_types=1);
use Pymt_Vas\Dependencies\Jose\Component\Console\AddKeyIntoKeysetCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\EcKeyGeneratorCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\EcKeysetGeneratorCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\GetThumbprintCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\KeyAnalyzerCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\KeyFileLoaderCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\KeysetAnalyzerCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\MergeKeysetCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\NoneKeyGeneratorCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\OctKeyGeneratorCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\OctKeysetGeneratorCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\OkpKeyGeneratorCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\OkpKeysetGeneratorCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\OptimizeRsaKeyCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\P12CertificateLoaderCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\PemConverterCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\PublicKeyCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\PublicKeysetCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\RotateKeysetCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\RsaKeyGeneratorCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\RsaKeysetGeneratorCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\SecretKeyGeneratorCommand;
use Pymt_Vas\Dependencies\Jose\Component\Console\X509CertificateLoaderCommand;
use Pymt_Vas\Dependencies\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
return function (ContainerConfigurator $container): void {
    $container = $container->services()->defaults()->private()->autoconfigure()->autowire();
    $container->set(AddKeyIntoKeysetCommand::class);
    $container->set(EcKeyGeneratorCommand::class);
    $container->set(EcKeysetGeneratorCommand::class);
    $container->set(GetThumbprintCommand::class);
    $container->set(OptimizeRsaKeyCommand::class);
    $container->set(KeyAnalyzerCommand::class);
    $container->set(KeyFileLoaderCommand::class);
    $container->set(KeysetAnalyzerCommand::class);
    $container->set(MergeKeysetCommand::class);
    $container->set(NoneKeyGeneratorCommand::class);
    $container->set(OctKeyGeneratorCommand::class);
    $container->set(OctKeysetGeneratorCommand::class);
    $container->set(OkpKeyGeneratorCommand::class);
    $container->set(OkpKeysetGeneratorCommand::class);
    $container->set(P12CertificateLoaderCommand::class);
    $container->set(PemConverterCommand::class);
    $container->set(PublicKeyCommand::class);
    $container->set(PublicKeysetCommand::class);
    $container->set(RotateKeysetCommand::class);
    $container->set(RsaKeyGeneratorCommand::class);
    $container->set(RsaKeysetGeneratorCommand::class);
    $container->set(SecretKeyGeneratorCommand::class);
    $container->set(X509CertificateLoaderCommand::class);
};