<?php

/**
 * BillingAgreementsApi
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
namespace Pymt_Vas\Dependencies\CyberSource\Api;

use Pymt_Vas\Dependencies\CyberSource\ApiClient;
use Pymt_Vas\Dependencies\CyberSource\ApiException;
use Pymt_Vas\Dependencies\CyberSource\Configuration;
use Pymt_Vas\Dependencies\CyberSource\ObjectSerializer;
use Pymt_Vas\Dependencies\CyberSource\Logging\LogFactory as LogFactory;
use Pymt_Vas\Dependencies\CyberSource\Authentication\Util\MLEUtility;
use Pymt_Vas\Dependencies\CyberSource\Utilities\MultipartHelpers\MultipartHelper;
use Exception;
/**
 * BillingAgreementsApi Class Doc Comment
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BillingAgreementsApi
{
    private static $logger = null;
    /**
     * API Client
     *
     * @var \Pymt_Vas\Dependencies\CyberSource\ApiClient instance of the ApiClient
     */
    protected $apiClient;
    /**
     * Constructor
     *
     * @param \Pymt_Vas\Dependencies\CyberSource\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Pymt_Vas\Dependencies\CyberSource\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }
        $this->apiClient = $apiClient;
        if (self::$logger === null) {
            self::$logger = (new LogFactory())->getLogger(\Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ClassHelper::getClassName(get_class($this)), $apiClient->merchantConfig->getLogConfiguration());
        }
    }
    /**
     * Get API client
     *
     * @return \Pymt_Vas\Dependencies\CyberSource\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
    /**
     * Set the API client
     *
     * @param \Pymt_Vas\Dependencies\CyberSource\ApiClient $apiClient set the API client
     *
     * @return BillingAgreementsApi
     */
    public function setApiClient(\Pymt_Vas\Dependencies\CyberSource\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
    /**
     * Operation billingAgreementsDeRegistration
     *
     * Modify a Billing Agreement
     *
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\ModifyBillingAgreement $modifyBillingAgreement  (required)
     * @param string $id ID for de-registration or cancellation of Billing Agreement (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2ModifyBillingAgreementPost201Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function billingAgreementsDeRegistration($modifyBillingAgreement, $id)
    {
        self::$logger->info('CALL TO METHOD billingAgreementsDeRegistration STARTED');
        list($response, $statusCode, $httpHeader) = $this->billingAgreementsDeRegistrationWithHttpInfo($modifyBillingAgreement, $id);
        self::$logger->info('CALL TO METHOD billingAgreementsDeRegistration ENDED');
        self::$logger->close();
        return [$response, $statusCode, $httpHeader];
    }
    /**
     * Operation billingAgreementsDeRegistrationWithHttpInfo
     *
     * Modify a Billing Agreement
     *
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\ModifyBillingAgreement $modifyBillingAgreement  (required)
     * @param string $id ID for de-registration or cancellation of Billing Agreement (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2ModifyBillingAgreementPost201Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function billingAgreementsDeRegistrationWithHttpInfo($modifyBillingAgreement, $id)
    {
        // verify the required parameter 'modifyBillingAgreement' is set
        if ($modifyBillingAgreement === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$modifyBillingAgreement} when calling billingAgreementsDeRegistration");
            throw new \InvalidArgumentException('Missing the required parameter $modifyBillingAgreement when calling billingAgreementsDeRegistration');
        }
        // verify the required parameter 'id' is set
        if ($id === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$id} when calling billingAgreementsDeRegistration");
            throw new \InvalidArgumentException('Missing the required parameter $id when calling billingAgreementsDeRegistration');
        }
        // parse inputs
        $resourcePath = "/pts/v2/billing-agreements/{id}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/hal+json;charset=utf-8']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json;charset=utf-8']);
        // path params
        if ($id !== null) {
            $resourcePath = str_replace("{" . "id" . "}", $this->apiClient->getSerializer()->toPathValue($id), $resourcePath);
        }
        // body params
        $_tempBody = null;
        if (isset($modifyBillingAgreement)) {
            $_tempBody = $modifyBillingAgreement;
        }
        $sdkTracker = new \Pymt_Vas\Dependencies\CyberSource\Utilities\Tracking\SdkTracker();
        $modelClassLocation = explode('\\', '\Pymt_Vas\Dependencies\CyberSource\Model\ModifyBillingAgreement');
        $_tempBody = $sdkTracker->insertDeveloperIdTracker($_tempBody, end($modelClassLocation), $this->apiClient->merchantConfig->getRunEnvironment(), $this->apiClient->merchantConfig->getDefaultDeveloperId());
        // for model (json/xml)
        if (isset($_tempBody) and count($formParams) <= 0) {
            $httpBody = $_tempBody;
            // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = MultipartHelper::build_data_files($boundary, $formParams);
            // for HTTP post (form)
        }
        //MLE check and mle encryption for req body
        $inboundMLEStatus = 'optional';
        if (MLEUtility::checkIsMLEForAPI($this->apiClient->merchantConfig, $inboundMLEStatus, "billingAgreementsDeRegistration,billingAgreementsDeRegistrationWithHttpInfo")) {
            try {
                $httpBody = MLEUtility::encryptRequestPayload($this->apiClient->merchantConfig, $httpBody);
            } catch (Exception $e) {
                self::$logger->error("Failed to encrypt request body:  {$e}");
                throw new ApiException("Failed to encrypt request body : " . $e->getMessage());
            }
        }
        // Logging
        self::$logger->debug("Resource : PATCH {$resourcePath}");
        if (isset($httpBody) and count($formParams) <= 0) {
            if ($this->apiClient->merchantConfig->getLogConfiguration()->isMaskingEnabled()) {
                $printHttpBody = \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\DataMasker::maskData($httpBody);
            } else {
                $printHttpBody = $httpBody;
            }
            self::$logger->debug("Body Parameter :\n" . $printHttpBody);
        }
        self::$logger->debug("Return Type : \\CyberSource\\Model\\PtsV2ModifyBillingAgreementPost201Response");
        // Response MLE check
        $isResponseMLEForAPI = MLEUtility::checkIsResponseMLEForAPI($this->apiClient->merchantConfig, "billingAgreementsDeRegistration,billingAgreementsDeRegistrationWithHttpInfo");
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi($resourcePath, 'PATCH', $queryParams, $httpBody, $headerParams, '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2ModifyBillingAgreementPost201Response', '/pts/v2/billing-agreements/{id}', $isResponseMLEForAPI);
            self::$logger->debug("Response Headers :\n" . \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ListHelper::toString($httpHeader));
            return [$this->apiClient->getSerializer()->deserialize($response, '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2ModifyBillingAgreementPost201Response', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2ModifyBillingAgreementPost201Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreateBillingAgreementPost400Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 502:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreateBillingAgreementPost502Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            self::$logger->error("ApiException : {$e}");
            throw $e;
        }
    }
    /**
     * Operation billingAgreementsIntimation
     *
     * Standing Instruction intimation
     *
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\IntimateBillingAgreement $intimateBillingAgreement  (required)
     * @param string $id ID for intimation of Billing Agreement (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreditsPost201Response1, HTTP status code, HTTP response headers (array of strings)
     */
    public function billingAgreementsIntimation($intimateBillingAgreement, $id)
    {
        self::$logger->info('CALL TO METHOD billingAgreementsIntimation STARTED');
        list($response, $statusCode, $httpHeader) = $this->billingAgreementsIntimationWithHttpInfo($intimateBillingAgreement, $id);
        self::$logger->info('CALL TO METHOD billingAgreementsIntimation ENDED');
        self::$logger->close();
        return [$response, $statusCode, $httpHeader];
    }
    /**
     * Operation billingAgreementsIntimationWithHttpInfo
     *
     * Standing Instruction intimation
     *
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\IntimateBillingAgreement $intimateBillingAgreement  (required)
     * @param string $id ID for intimation of Billing Agreement (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreditsPost201Response1, HTTP status code, HTTP response headers (array of strings)
     */
    public function billingAgreementsIntimationWithHttpInfo($intimateBillingAgreement, $id)
    {
        // verify the required parameter 'intimateBillingAgreement' is set
        if ($intimateBillingAgreement === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$intimateBillingAgreement} when calling billingAgreementsIntimation");
            throw new \InvalidArgumentException('Missing the required parameter $intimateBillingAgreement when calling billingAgreementsIntimation');
        }
        // verify the required parameter 'id' is set
        if ($id === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$id} when calling billingAgreementsIntimation");
            throw new \InvalidArgumentException('Missing the required parameter $id when calling billingAgreementsIntimation');
        }
        // parse inputs
        $resourcePath = "/pts/v2/billing-agreements/{id}/intimations";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/hal+json;charset=utf-8']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json;charset=utf-8']);
        // path params
        if ($id !== null) {
            $resourcePath = str_replace("{" . "id" . "}", $this->apiClient->getSerializer()->toPathValue($id), $resourcePath);
        }
        // body params
        $_tempBody = null;
        if (isset($intimateBillingAgreement)) {
            $_tempBody = $intimateBillingAgreement;
        }
        $sdkTracker = new \Pymt_Vas\Dependencies\CyberSource\Utilities\Tracking\SdkTracker();
        $modelClassLocation = explode('\\', '\Pymt_Vas\Dependencies\CyberSource\Model\IntimateBillingAgreement');
        $_tempBody = $sdkTracker->insertDeveloperIdTracker($_tempBody, end($modelClassLocation), $this->apiClient->merchantConfig->getRunEnvironment(), $this->apiClient->merchantConfig->getDefaultDeveloperId());
        // for model (json/xml)
        if (isset($_tempBody) and count($formParams) <= 0) {
            $httpBody = $_tempBody;
            // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = MultipartHelper::build_data_files($boundary, $formParams);
            // for HTTP post (form)
        }
        //MLE check and mle encryption for req body
        $inboundMLEStatus = 'optional';
        if (MLEUtility::checkIsMLEForAPI($this->apiClient->merchantConfig, $inboundMLEStatus, "billingAgreementsIntimation,billingAgreementsIntimationWithHttpInfo")) {
            try {
                $httpBody = MLEUtility::encryptRequestPayload($this->apiClient->merchantConfig, $httpBody);
            } catch (Exception $e) {
                self::$logger->error("Failed to encrypt request body:  {$e}");
                throw new ApiException("Failed to encrypt request body : " . $e->getMessage());
            }
        }
        // Logging
        self::$logger->debug("Resource : POST {$resourcePath}");
        if (isset($httpBody) and count($formParams) <= 0) {
            if ($this->apiClient->merchantConfig->getLogConfiguration()->isMaskingEnabled()) {
                $printHttpBody = \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\DataMasker::maskData($httpBody);
            } else {
                $printHttpBody = $httpBody;
            }
            self::$logger->debug("Body Parameter :\n" . $printHttpBody);
        }
        self::$logger->debug("Return Type : \\CyberSource\\Model\\PtsV2CreditsPost201Response1");
        // Response MLE check
        $isResponseMLEForAPI = MLEUtility::checkIsResponseMLEForAPI($this->apiClient->merchantConfig, "billingAgreementsIntimation,billingAgreementsIntimationWithHttpInfo");
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi($resourcePath, 'POST', $queryParams, $httpBody, $headerParams, '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreditsPost201Response1', '/pts/v2/billing-agreements/{id}/intimations', $isResponseMLEForAPI);
            self::$logger->debug("Response Headers :\n" . \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ListHelper::toString($httpHeader));
            return [$this->apiClient->getSerializer()->deserialize($response, '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreditsPost201Response1', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreditsPost201Response1', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreateBillingAgreementPost400Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 502:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreateBillingAgreementPost502Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            self::$logger->error("ApiException : {$e}");
            throw $e;
        }
    }
    /**
     * Operation billingAgreementsRegistration
     *
     * Create a Billing Agreement
     *
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\CreateBillingAgreement $createBillingAgreement  (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreateBillingAgreementPost201Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function billingAgreementsRegistration($createBillingAgreement)
    {
        self::$logger->info('CALL TO METHOD billingAgreementsRegistration STARTED');
        list($response, $statusCode, $httpHeader) = $this->billingAgreementsRegistrationWithHttpInfo($createBillingAgreement);
        self::$logger->info('CALL TO METHOD billingAgreementsRegistration ENDED');
        self::$logger->close();
        return [$response, $statusCode, $httpHeader];
    }
    /**
     * Operation billingAgreementsRegistrationWithHttpInfo
     *
     * Create a Billing Agreement
     *
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\CreateBillingAgreement $createBillingAgreement  (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreateBillingAgreementPost201Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function billingAgreementsRegistrationWithHttpInfo($createBillingAgreement)
    {
        // verify the required parameter 'createBillingAgreement' is set
        if ($createBillingAgreement === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$createBillingAgreement} when calling billingAgreementsRegistration");
            throw new \InvalidArgumentException('Missing the required parameter $createBillingAgreement when calling billingAgreementsRegistration');
        }
        // parse inputs
        $resourcePath = "/pts/v2/billing-agreements";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/hal+json;charset=utf-8']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json;charset=utf-8']);
        // body params
        $_tempBody = null;
        if (isset($createBillingAgreement)) {
            $_tempBody = $createBillingAgreement;
        }
        $sdkTracker = new \Pymt_Vas\Dependencies\CyberSource\Utilities\Tracking\SdkTracker();
        $modelClassLocation = explode('\\', '\Pymt_Vas\Dependencies\CyberSource\Model\CreateBillingAgreement');
        $_tempBody = $sdkTracker->insertDeveloperIdTracker($_tempBody, end($modelClassLocation), $this->apiClient->merchantConfig->getRunEnvironment(), $this->apiClient->merchantConfig->getDefaultDeveloperId());
        // for model (json/xml)
        if (isset($_tempBody) and count($formParams) <= 0) {
            $httpBody = $_tempBody;
            // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = MultipartHelper::build_data_files($boundary, $formParams);
            // for HTTP post (form)
        }
        //MLE check and mle encryption for req body
        $inboundMLEStatus = 'optional';
        if (MLEUtility::checkIsMLEForAPI($this->apiClient->merchantConfig, $inboundMLEStatus, "billingAgreementsRegistration,billingAgreementsRegistrationWithHttpInfo")) {
            try {
                $httpBody = MLEUtility::encryptRequestPayload($this->apiClient->merchantConfig, $httpBody);
            } catch (Exception $e) {
                self::$logger->error("Failed to encrypt request body:  {$e}");
                throw new ApiException("Failed to encrypt request body : " . $e->getMessage());
            }
        }
        // Logging
        self::$logger->debug("Resource : POST {$resourcePath}");
        if (isset($httpBody) and count($formParams) <= 0) {
            if ($this->apiClient->merchantConfig->getLogConfiguration()->isMaskingEnabled()) {
                $printHttpBody = \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\DataMasker::maskData($httpBody);
            } else {
                $printHttpBody = $httpBody;
            }
            self::$logger->debug("Body Parameter :\n" . $printHttpBody);
        }
        self::$logger->debug("Return Type : \\CyberSource\\Model\\PtsV2CreateBillingAgreementPost201Response");
        // Response MLE check
        $isResponseMLEForAPI = MLEUtility::checkIsResponseMLEForAPI($this->apiClient->merchantConfig, "billingAgreementsRegistration,billingAgreementsRegistrationWithHttpInfo");
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi($resourcePath, 'POST', $queryParams, $httpBody, $headerParams, '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreateBillingAgreementPost201Response', '/pts/v2/billing-agreements', $isResponseMLEForAPI);
            self::$logger->debug("Response Headers :\n" . \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ListHelper::toString($httpHeader));
            return [$this->apiClient->getSerializer()->deserialize($response, '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreateBillingAgreementPost201Response', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreateBillingAgreementPost201Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreateBillingAgreementPost400Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 502:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\PtsV2CreateBillingAgreementPost502Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            self::$logger->error("ApiException : {$e}");
            throw $e;
        }
    }
}