<?php

/**
 * InstructionsApi
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
namespace Pymt_Vas\Dependencies\CyberSource\Api;

use Pymt_Vas\Dependencies\CyberSource\ApiClient;
use Pymt_Vas\Dependencies\CyberSource\ApiException;
use Pymt_Vas\Dependencies\CyberSource\Configuration;
use Pymt_Vas\Dependencies\CyberSource\ObjectSerializer;
use Pymt_Vas\Dependencies\CyberSource\Logging\LogFactory as LogFactory;
use Pymt_Vas\Dependencies\CyberSource\Authentication\Util\MLEUtility;
use Pymt_Vas\Dependencies\CyberSource\Utilities\MultipartHelpers\MultipartHelper;
use Exception;
/**
 * InstructionsApi Class Doc Comment
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstructionsApi
{
    private static $logger = null;
    /**
     * API Client
     *
     * @var \Pymt_Vas\Dependencies\CyberSource\ApiClient instance of the ApiClient
     */
    protected $apiClient;
    /**
     * Constructor
     *
     * @param \Pymt_Vas\Dependencies\CyberSource\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Pymt_Vas\Dependencies\CyberSource\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }
        $this->apiClient = $apiClient;
        if (self::$logger === null) {
            self::$logger = (new LogFactory())->getLogger(\Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ClassHelper::getClassName(get_class($this)), $apiClient->merchantConfig->getLogConfiguration());
        }
    }
    /**
     * Get API client
     *
     * @return \Pymt_Vas\Dependencies\CyberSource\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
    /**
     * Set the API client
     *
     * @param \Pymt_Vas\Dependencies\CyberSource\ApiClient $apiClient set the API client
     *
     * @return InstructionsApi
     */
    public function setApiClient(\Pymt_Vas\Dependencies\CyberSource\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
    /**
     * Operation cancelPurchaseIntent
     *
     * Cancel a purchase intent
     *
     * @param string $instructionId  (required)
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCancelPurchaseIntentRequest $agenticCancelPurchaseIntentRequest Unique identifier for the purchase intent instruction. (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200, HTTP status code, HTTP response headers (array of strings)
     */
    public function cancelPurchaseIntent($instructionId, $agenticCancelPurchaseIntentRequest)
    {
        self::$logger->info('CALL TO METHOD cancelPurchaseIntent STARTED');
        list($response, $statusCode, $httpHeader) = $this->cancelPurchaseIntentWithHttpInfo($instructionId, $agenticCancelPurchaseIntentRequest);
        self::$logger->info('CALL TO METHOD cancelPurchaseIntent ENDED');
        self::$logger->close();
        return [$response, $statusCode, $httpHeader];
    }
    /**
     * Operation cancelPurchaseIntentWithHttpInfo
     *
     * Cancel a purchase intent
     *
     * @param string $instructionId  (required)
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCancelPurchaseIntentRequest $agenticCancelPurchaseIntentRequest Unique identifier for the purchase intent instruction. (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200, HTTP status code, HTTP response headers (array of strings)
     */
    public function cancelPurchaseIntentWithHttpInfo($instructionId, $agenticCancelPurchaseIntentRequest)
    {
        // verify the required parameter 'instructionId' is set
        if ($instructionId === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$instructionId} when calling cancelPurchaseIntent");
            throw new \InvalidArgumentException('Missing the required parameter $instructionId when calling cancelPurchaseIntent');
        }
        // verify the required parameter 'agenticCancelPurchaseIntentRequest' is set
        if ($agenticCancelPurchaseIntentRequest === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$agenticCancelPurchaseIntentRequest} when calling cancelPurchaseIntent");
            throw new \InvalidArgumentException('Missing the required parameter $agenticCancelPurchaseIntentRequest when calling cancelPurchaseIntent');
        }
        // parse inputs
        $resourcePath = "/acp/v1/instructions/{instructionId}/cancel";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/hal+json;charset=utf-8']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json;charset=utf-8']);
        // path params
        if ($instructionId !== null) {
            $resourcePath = str_replace("{" . "instructionId" . "}", $this->apiClient->getSerializer()->toPathValue($instructionId), $resourcePath);
        }
        // body params
        $_tempBody = null;
        if (isset($agenticCancelPurchaseIntentRequest)) {
            $_tempBody = $agenticCancelPurchaseIntentRequest;
        }
        $sdkTracker = new \Pymt_Vas\Dependencies\CyberSource\Utilities\Tracking\SdkTracker();
        $modelClassLocation = explode('\\', '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCancelPurchaseIntentRequest');
        $_tempBody = $sdkTracker->insertDeveloperIdTracker($_tempBody, end($modelClassLocation), $this->apiClient->merchantConfig->getRunEnvironment(), $this->apiClient->merchantConfig->getDefaultDeveloperId());
        // for model (json/xml)
        if (isset($_tempBody) and count($formParams) <= 0) {
            $httpBody = $_tempBody;
            // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = MultipartHelper::build_data_files($boundary, $formParams);
            // for HTTP post (form)
        }
        //MLE check and mle encryption for req body
        $inboundMLEStatus = 'mandatory';
        if (MLEUtility::checkIsMLEForAPI($this->apiClient->merchantConfig, $inboundMLEStatus, "cancelPurchaseIntent,cancelPurchaseIntentWithHttpInfo")) {
            try {
                $httpBody = MLEUtility::encryptRequestPayload($this->apiClient->merchantConfig, $httpBody);
            } catch (Exception $e) {
                self::$logger->error("Failed to encrypt request body:  {$e}");
                throw new ApiException("Failed to encrypt request body : " . $e->getMessage());
            }
        }
        // Logging
        self::$logger->debug("Resource : PUT {$resourcePath}");
        if (isset($httpBody) and count($formParams) <= 0) {
            if ($this->apiClient->merchantConfig->getLogConfiguration()->isMaskingEnabled()) {
                $printHttpBody = \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\DataMasker::maskData($httpBody);
            } else {
                $printHttpBody = $httpBody;
            }
            self::$logger->debug("Body Parameter :\n" . $printHttpBody);
        }
        self::$logger->debug("Return Type : \\CyberSource\\Model\\AgenticCreatePurchaseIntentResponse200");
        // Response MLE check
        $isResponseMLEForAPI = MLEUtility::checkIsResponseMLEForAPI($this->apiClient->merchantConfig, "cancelPurchaseIntent,cancelPurchaseIntentWithHttpInfo");
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi($resourcePath, 'PUT', $queryParams, $httpBody, $headerParams, '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200', '/acp/v1/instructions/{instructionId}/cancel', $isResponseMLEForAPI);
            self::$logger->debug("Response Headers :\n" . \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ListHelper::toString($httpHeader));
            return [$this->apiClient->getSerializer()->deserialize($response, '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 202:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticPendingPurchaseIntentResponse202', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            self::$logger->error("ApiException : {$e}");
            throw $e;
        }
    }
    /**
     * Operation confirmTransactionEvents
     *
     * Confirm transaction events
     *
     * @param string $instructionId Unique identifier for the purchase intent instruction. (required)
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticConfirmTransactionEventsRequest $agenticConfirmTransactionEventsRequest  (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticConfirmTransactionEventsResponse202, HTTP status code, HTTP response headers (array of strings)
     */
    public function confirmTransactionEvents($instructionId, $agenticConfirmTransactionEventsRequest)
    {
        self::$logger->info('CALL TO METHOD confirmTransactionEvents STARTED');
        list($response, $statusCode, $httpHeader) = $this->confirmTransactionEventsWithHttpInfo($instructionId, $agenticConfirmTransactionEventsRequest);
        self::$logger->info('CALL TO METHOD confirmTransactionEvents ENDED');
        self::$logger->close();
        return [$response, $statusCode, $httpHeader];
    }
    /**
     * Operation confirmTransactionEventsWithHttpInfo
     *
     * Confirm transaction events
     *
     * @param string $instructionId Unique identifier for the purchase intent instruction. (required)
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticConfirmTransactionEventsRequest $agenticConfirmTransactionEventsRequest  (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticConfirmTransactionEventsResponse202, HTTP status code, HTTP response headers (array of strings)
     */
    public function confirmTransactionEventsWithHttpInfo($instructionId, $agenticConfirmTransactionEventsRequest)
    {
        // verify the required parameter 'instructionId' is set
        if ($instructionId === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$instructionId} when calling confirmTransactionEvents");
            throw new \InvalidArgumentException('Missing the required parameter $instructionId when calling confirmTransactionEvents');
        }
        // verify the required parameter 'agenticConfirmTransactionEventsRequest' is set
        if ($agenticConfirmTransactionEventsRequest === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$agenticConfirmTransactionEventsRequest} when calling confirmTransactionEvents");
            throw new \InvalidArgumentException('Missing the required parameter $agenticConfirmTransactionEventsRequest when calling confirmTransactionEvents');
        }
        // parse inputs
        $resourcePath = "/acp/v1/instructions/{instructionId}/confirmations";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/hal+json;charset=utf-8']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json;charset=utf-8']);
        // path params
        if ($instructionId !== null) {
            $resourcePath = str_replace("{" . "instructionId" . "}", $this->apiClient->getSerializer()->toPathValue($instructionId), $resourcePath);
        }
        // body params
        $_tempBody = null;
        if (isset($agenticConfirmTransactionEventsRequest)) {
            $_tempBody = $agenticConfirmTransactionEventsRequest;
        }
        $sdkTracker = new \Pymt_Vas\Dependencies\CyberSource\Utilities\Tracking\SdkTracker();
        $modelClassLocation = explode('\\', '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticConfirmTransactionEventsRequest');
        $_tempBody = $sdkTracker->insertDeveloperIdTracker($_tempBody, end($modelClassLocation), $this->apiClient->merchantConfig->getRunEnvironment(), $this->apiClient->merchantConfig->getDefaultDeveloperId());
        // for model (json/xml)
        if (isset($_tempBody) and count($formParams) <= 0) {
            $httpBody = $_tempBody;
            // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = MultipartHelper::build_data_files($boundary, $formParams);
            // for HTTP post (form)
        }
        //MLE check and mle encryption for req body
        $inboundMLEStatus = 'mandatory';
        if (MLEUtility::checkIsMLEForAPI($this->apiClient->merchantConfig, $inboundMLEStatus, "confirmTransactionEvents,confirmTransactionEventsWithHttpInfo")) {
            try {
                $httpBody = MLEUtility::encryptRequestPayload($this->apiClient->merchantConfig, $httpBody);
            } catch (Exception $e) {
                self::$logger->error("Failed to encrypt request body:  {$e}");
                throw new ApiException("Failed to encrypt request body : " . $e->getMessage());
            }
        }
        // Logging
        self::$logger->debug("Resource : POST {$resourcePath}");
        if (isset($httpBody) and count($formParams) <= 0) {
            if ($this->apiClient->merchantConfig->getLogConfiguration()->isMaskingEnabled()) {
                $printHttpBody = \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\DataMasker::maskData($httpBody);
            } else {
                $printHttpBody = $httpBody;
            }
            self::$logger->debug("Body Parameter :\n" . $printHttpBody);
        }
        self::$logger->debug("Return Type : \\CyberSource\\Model\\AgenticConfirmTransactionEventsResponse202");
        // Response MLE check
        $isResponseMLEForAPI = MLEUtility::checkIsResponseMLEForAPI($this->apiClient->merchantConfig, "confirmTransactionEvents,confirmTransactionEventsWithHttpInfo");
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi($resourcePath, 'POST', $queryParams, $httpBody, $headerParams, '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticConfirmTransactionEventsResponse202', '/acp/v1/instructions/{instructionId}/confirmations', $isResponseMLEForAPI);
            self::$logger->debug("Response Headers :\n" . \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ListHelper::toString($httpHeader));
            return [$this->apiClient->getSerializer()->deserialize($response, '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticConfirmTransactionEventsResponse202', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticConfirmTransactionEventsResponse202', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            self::$logger->error("ApiException : {$e}");
            throw $e;
        }
    }
    /**
     * Operation initiatePurchaseIntent
     *
     * Initiate a purchase intent
     *
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentRequest $agenticCreatePurchaseIntentRequest  (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200, HTTP status code, HTTP response headers (array of strings)
     */
    public function initiatePurchaseIntent($agenticCreatePurchaseIntentRequest)
    {
        self::$logger->info('CALL TO METHOD initiatePurchaseIntent STARTED');
        list($response, $statusCode, $httpHeader) = $this->initiatePurchaseIntentWithHttpInfo($agenticCreatePurchaseIntentRequest);
        self::$logger->info('CALL TO METHOD initiatePurchaseIntent ENDED');
        self::$logger->close();
        return [$response, $statusCode, $httpHeader];
    }
    /**
     * Operation initiatePurchaseIntentWithHttpInfo
     *
     * Initiate a purchase intent
     *
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentRequest $agenticCreatePurchaseIntentRequest  (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200, HTTP status code, HTTP response headers (array of strings)
     */
    public function initiatePurchaseIntentWithHttpInfo($agenticCreatePurchaseIntentRequest)
    {
        // verify the required parameter 'agenticCreatePurchaseIntentRequest' is set
        if ($agenticCreatePurchaseIntentRequest === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$agenticCreatePurchaseIntentRequest} when calling initiatePurchaseIntent");
            throw new \InvalidArgumentException('Missing the required parameter $agenticCreatePurchaseIntentRequest when calling initiatePurchaseIntent');
        }
        // parse inputs
        $resourcePath = "/acp/v1/instructions";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/hal+json;charset=utf-8']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json;charset=utf-8']);
        // body params
        $_tempBody = null;
        if (isset($agenticCreatePurchaseIntentRequest)) {
            $_tempBody = $agenticCreatePurchaseIntentRequest;
        }
        $sdkTracker = new \Pymt_Vas\Dependencies\CyberSource\Utilities\Tracking\SdkTracker();
        $modelClassLocation = explode('\\', '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentRequest');
        $_tempBody = $sdkTracker->insertDeveloperIdTracker($_tempBody, end($modelClassLocation), $this->apiClient->merchantConfig->getRunEnvironment(), $this->apiClient->merchantConfig->getDefaultDeveloperId());
        // for model (json/xml)
        if (isset($_tempBody) and count($formParams) <= 0) {
            $httpBody = $_tempBody;
            // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = MultipartHelper::build_data_files($boundary, $formParams);
            // for HTTP post (form)
        }
        //MLE check and mle encryption for req body
        $inboundMLEStatus = 'mandatory';
        if (MLEUtility::checkIsMLEForAPI($this->apiClient->merchantConfig, $inboundMLEStatus, "initiatePurchaseIntent,initiatePurchaseIntentWithHttpInfo")) {
            try {
                $httpBody = MLEUtility::encryptRequestPayload($this->apiClient->merchantConfig, $httpBody);
            } catch (Exception $e) {
                self::$logger->error("Failed to encrypt request body:  {$e}");
                throw new ApiException("Failed to encrypt request body : " . $e->getMessage());
            }
        }
        // Logging
        self::$logger->debug("Resource : POST {$resourcePath}");
        if (isset($httpBody) and count($formParams) <= 0) {
            if ($this->apiClient->merchantConfig->getLogConfiguration()->isMaskingEnabled()) {
                $printHttpBody = \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\DataMasker::maskData($httpBody);
            } else {
                $printHttpBody = $httpBody;
            }
            self::$logger->debug("Body Parameter :\n" . $printHttpBody);
        }
        self::$logger->debug("Return Type : \\CyberSource\\Model\\AgenticCreatePurchaseIntentResponse200");
        // Response MLE check
        $isResponseMLEForAPI = MLEUtility::checkIsResponseMLEForAPI($this->apiClient->merchantConfig, "initiatePurchaseIntent,initiatePurchaseIntentWithHttpInfo");
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi($resourcePath, 'POST', $queryParams, $httpBody, $headerParams, '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200', '/acp/v1/instructions', $isResponseMLEForAPI);
            self::$logger->debug("Response Headers :\n" . \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ListHelper::toString($httpHeader));
            return [$this->apiClient->getSerializer()->deserialize($response, '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 202:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticPendingPurchaseIntentResponse202', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            self::$logger->error("ApiException : {$e}");
            throw $e;
        }
    }
    /**
     * Operation retrievePaymentCredentials
     *
     * Retrieve payment credentials
     *
     * @param string $instructionId Unique identifier for the purchase intent instruction. (required)
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticRetrievePaymentCredentialsRequest $agenticRetrievePaymentCredentialsRequest  (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticRetrievePaymentCredentialsResponse200, HTTP status code, HTTP response headers (array of strings)
     */
    public function retrievePaymentCredentials($instructionId, $agenticRetrievePaymentCredentialsRequest)
    {
        self::$logger->info('CALL TO METHOD retrievePaymentCredentials STARTED');
        list($response, $statusCode, $httpHeader) = $this->retrievePaymentCredentialsWithHttpInfo($instructionId, $agenticRetrievePaymentCredentialsRequest);
        self::$logger->info('CALL TO METHOD retrievePaymentCredentials ENDED');
        self::$logger->close();
        return [$response, $statusCode, $httpHeader];
    }
    /**
     * Operation retrievePaymentCredentialsWithHttpInfo
     *
     * Retrieve payment credentials
     *
     * @param string $instructionId Unique identifier for the purchase intent instruction. (required)
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticRetrievePaymentCredentialsRequest $agenticRetrievePaymentCredentialsRequest  (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticRetrievePaymentCredentialsResponse200, HTTP status code, HTTP response headers (array of strings)
     */
    public function retrievePaymentCredentialsWithHttpInfo($instructionId, $agenticRetrievePaymentCredentialsRequest)
    {
        // verify the required parameter 'instructionId' is set
        if ($instructionId === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$instructionId} when calling retrievePaymentCredentials");
            throw new \InvalidArgumentException('Missing the required parameter $instructionId when calling retrievePaymentCredentials');
        }
        // verify the required parameter 'agenticRetrievePaymentCredentialsRequest' is set
        if ($agenticRetrievePaymentCredentialsRequest === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$agenticRetrievePaymentCredentialsRequest} when calling retrievePaymentCredentials");
            throw new \InvalidArgumentException('Missing the required parameter $agenticRetrievePaymentCredentialsRequest when calling retrievePaymentCredentials');
        }
        // parse inputs
        $resourcePath = "/acp/v1/instructions/{instructionId}/credentials";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/hal+json;charset=utf-8']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json;charset=utf-8']);
        // path params
        if ($instructionId !== null) {
            $resourcePath = str_replace("{" . "instructionId" . "}", $this->apiClient->getSerializer()->toPathValue($instructionId), $resourcePath);
        }
        // body params
        $_tempBody = null;
        if (isset($agenticRetrievePaymentCredentialsRequest)) {
            $_tempBody = $agenticRetrievePaymentCredentialsRequest;
        }
        $sdkTracker = new \Pymt_Vas\Dependencies\CyberSource\Utilities\Tracking\SdkTracker();
        $modelClassLocation = explode('\\', '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticRetrievePaymentCredentialsRequest');
        $_tempBody = $sdkTracker->insertDeveloperIdTracker($_tempBody, end($modelClassLocation), $this->apiClient->merchantConfig->getRunEnvironment(), $this->apiClient->merchantConfig->getDefaultDeveloperId());
        // for model (json/xml)
        if (isset($_tempBody) and count($formParams) <= 0) {
            $httpBody = $_tempBody;
            // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = MultipartHelper::build_data_files($boundary, $formParams);
            // for HTTP post (form)
        }
        //MLE check and mle encryption for req body
        $inboundMLEStatus = 'mandatory';
        if (MLEUtility::checkIsMLEForAPI($this->apiClient->merchantConfig, $inboundMLEStatus, "retrievePaymentCredentials,retrievePaymentCredentialsWithHttpInfo")) {
            try {
                $httpBody = MLEUtility::encryptRequestPayload($this->apiClient->merchantConfig, $httpBody);
            } catch (Exception $e) {
                self::$logger->error("Failed to encrypt request body:  {$e}");
                throw new ApiException("Failed to encrypt request body : " . $e->getMessage());
            }
        }
        // Logging
        self::$logger->debug("Resource : POST {$resourcePath}");
        if (isset($httpBody) and count($formParams) <= 0) {
            if ($this->apiClient->merchantConfig->getLogConfiguration()->isMaskingEnabled()) {
                $printHttpBody = \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\DataMasker::maskData($httpBody);
            } else {
                $printHttpBody = $httpBody;
            }
            self::$logger->debug("Body Parameter :\n" . $printHttpBody);
        }
        self::$logger->debug("Return Type : \\CyberSource\\Model\\AgenticRetrievePaymentCredentialsResponse200");
        // Response MLE check
        $isResponseMLEForAPI = MLEUtility::checkIsResponseMLEForAPI($this->apiClient->merchantConfig, "retrievePaymentCredentials,retrievePaymentCredentialsWithHttpInfo");
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi($resourcePath, 'POST', $queryParams, $httpBody, $headerParams, '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticRetrievePaymentCredentialsResponse200', '/acp/v1/instructions/{instructionId}/credentials', $isResponseMLEForAPI);
            self::$logger->debug("Response Headers :\n" . \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ListHelper::toString($httpHeader));
            return [$this->apiClient->getSerializer()->deserialize($response, '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticRetrievePaymentCredentialsResponse200', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticRetrievePaymentCredentialsResponse200', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            self::$logger->error("ApiException : {$e}");
            throw $e;
        }
    }
    /**
     * Operation updatePurchaseIntent
     *
     * Update a purchase intent
     *
     * @param string $instructionId Unique identifier for the purchase intent instruction. (required)
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticUpdatePurchaseIntentRequest $agenticUpdatePurchaseIntentRequest  (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200, HTTP status code, HTTP response headers (array of strings)
     */
    public function updatePurchaseIntent($instructionId, $agenticUpdatePurchaseIntentRequest)
    {
        self::$logger->info('CALL TO METHOD updatePurchaseIntent STARTED');
        list($response, $statusCode, $httpHeader) = $this->updatePurchaseIntentWithHttpInfo($instructionId, $agenticUpdatePurchaseIntentRequest);
        self::$logger->info('CALL TO METHOD updatePurchaseIntent ENDED');
        self::$logger->close();
        return [$response, $statusCode, $httpHeader];
    }
    /**
     * Operation updatePurchaseIntentWithHttpInfo
     *
     * Update a purchase intent
     *
     * @param string $instructionId Unique identifier for the purchase intent instruction. (required)
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticUpdatePurchaseIntentRequest $agenticUpdatePurchaseIntentRequest  (required)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200, HTTP status code, HTTP response headers (array of strings)
     */
    public function updatePurchaseIntentWithHttpInfo($instructionId, $agenticUpdatePurchaseIntentRequest)
    {
        // verify the required parameter 'instructionId' is set
        if ($instructionId === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$instructionId} when calling updatePurchaseIntent");
            throw new \InvalidArgumentException('Missing the required parameter $instructionId when calling updatePurchaseIntent');
        }
        // verify the required parameter 'agenticUpdatePurchaseIntentRequest' is set
        if ($agenticUpdatePurchaseIntentRequest === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$agenticUpdatePurchaseIntentRequest} when calling updatePurchaseIntent");
            throw new \InvalidArgumentException('Missing the required parameter $agenticUpdatePurchaseIntentRequest when calling updatePurchaseIntent');
        }
        // parse inputs
        $resourcePath = "/acp/v1/instructions/{instructionId}";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/hal+json;charset=utf-8']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json;charset=utf-8']);
        // path params
        if ($instructionId !== null) {
            $resourcePath = str_replace("{" . "instructionId" . "}", $this->apiClient->getSerializer()->toPathValue($instructionId), $resourcePath);
        }
        // body params
        $_tempBody = null;
        if (isset($agenticUpdatePurchaseIntentRequest)) {
            $_tempBody = $agenticUpdatePurchaseIntentRequest;
        }
        $sdkTracker = new \Pymt_Vas\Dependencies\CyberSource\Utilities\Tracking\SdkTracker();
        $modelClassLocation = explode('\\', '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticUpdatePurchaseIntentRequest');
        $_tempBody = $sdkTracker->insertDeveloperIdTracker($_tempBody, end($modelClassLocation), $this->apiClient->merchantConfig->getRunEnvironment(), $this->apiClient->merchantConfig->getDefaultDeveloperId());
        // for model (json/xml)
        if (isset($_tempBody) and count($formParams) <= 0) {
            $httpBody = $_tempBody;
            // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = MultipartHelper::build_data_files($boundary, $formParams);
            // for HTTP post (form)
        }
        //MLE check and mle encryption for req body
        $inboundMLEStatus = 'mandatory';
        if (MLEUtility::checkIsMLEForAPI($this->apiClient->merchantConfig, $inboundMLEStatus, "updatePurchaseIntent,updatePurchaseIntentWithHttpInfo")) {
            try {
                $httpBody = MLEUtility::encryptRequestPayload($this->apiClient->merchantConfig, $httpBody);
            } catch (Exception $e) {
                self::$logger->error("Failed to encrypt request body:  {$e}");
                throw new ApiException("Failed to encrypt request body : " . $e->getMessage());
            }
        }
        // Logging
        self::$logger->debug("Resource : PUT {$resourcePath}");
        if (isset($httpBody) and count($formParams) <= 0) {
            if ($this->apiClient->merchantConfig->getLogConfiguration()->isMaskingEnabled()) {
                $printHttpBody = \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\DataMasker::maskData($httpBody);
            } else {
                $printHttpBody = $httpBody;
            }
            self::$logger->debug("Body Parameter :\n" . $printHttpBody);
        }
        self::$logger->debug("Return Type : \\CyberSource\\Model\\AgenticCreatePurchaseIntentResponse200");
        // Response MLE check
        $isResponseMLEForAPI = MLEUtility::checkIsResponseMLEForAPI($this->apiClient->merchantConfig, "updatePurchaseIntent,updatePurchaseIntentWithHttpInfo");
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi($resourcePath, 'PUT', $queryParams, $httpBody, $headerParams, '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200', '/acp/v1/instructions/{instructionId}', $isResponseMLEForAPI);
            self::$logger->debug("Response Headers :\n" . \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ListHelper::toString($httpHeader));
            return [$this->apiClient->getSerializer()->deserialize($response, '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCreatePurchaseIntentResponse200', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 202:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticPendingPurchaseIntentResponse202', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\AgenticCardEnrollmentBadRequestResponse400', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            self::$logger->error("ApiException : {$e}");
            throw $e;
        }
    }
}