<?php

/**
 * InvoiceSettingsApi
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
namespace Pymt_Vas\Dependencies\CyberSource\Api;

use Pymt_Vas\Dependencies\CyberSource\ApiClient;
use Pymt_Vas\Dependencies\CyberSource\ApiException;
use Pymt_Vas\Dependencies\CyberSource\Configuration;
use Pymt_Vas\Dependencies\CyberSource\ObjectSerializer;
use Pymt_Vas\Dependencies\CyberSource\Logging\LogFactory as LogFactory;
use Pymt_Vas\Dependencies\CyberSource\Authentication\Util\MLEUtility;
use Pymt_Vas\Dependencies\CyberSource\Utilities\MultipartHelpers\MultipartHelper;
use Exception;
/**
 * InvoiceSettingsApi Class Doc Comment
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InvoiceSettingsApi
{
    private static $logger = null;
    /**
     * API Client
     *
     * @var \Pymt_Vas\Dependencies\CyberSource\ApiClient instance of the ApiClient
     */
    protected $apiClient;
    /**
     * Constructor
     *
     * @param \Pymt_Vas\Dependencies\CyberSource\ApiClient|null $apiClient The api client to use
     */
    public function __construct(\Pymt_Vas\Dependencies\CyberSource\ApiClient $apiClient = null)
    {
        if ($apiClient === null) {
            $apiClient = new ApiClient();
        }
        $this->apiClient = $apiClient;
        if (self::$logger === null) {
            self::$logger = (new LogFactory())->getLogger(\Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ClassHelper::getClassName(get_class($this)), $apiClient->merchantConfig->getLogConfiguration());
        }
    }
    /**
     * Get API client
     *
     * @return \Pymt_Vas\Dependencies\CyberSource\ApiClient get the API client
     */
    public function getApiClient()
    {
        return $this->apiClient;
    }
    /**
     * Set the API client
     *
     * @param \Pymt_Vas\Dependencies\CyberSource\ApiClient $apiClient set the API client
     *
     * @return InvoiceSettingsApi
     */
    public function setApiClient(\Pymt_Vas\Dependencies\CyberSource\ApiClient $apiClient)
    {
        $this->apiClient = $apiClient;
        return $this;
    }
    /**
     * Operation getInvoiceSettings
     *
     * Get Invoice Settings
     *
     * @param string $productType Allows you to choose which product type settings you want to update. (optional)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoiceSettingsGet200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getInvoiceSettings($productType = null)
    {
        self::$logger->info('CALL TO METHOD getInvoiceSettings STARTED');
        list($response, $statusCode, $httpHeader) = $this->getInvoiceSettingsWithHttpInfo($productType);
        self::$logger->info('CALL TO METHOD getInvoiceSettings ENDED');
        self::$logger->close();
        return [$response, $statusCode, $httpHeader];
    }
    /**
     * Operation getInvoiceSettingsWithHttpInfo
     *
     * Get Invoice Settings
     *
     * @param string $productType Allows you to choose which product type settings you want to update. (optional)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoiceSettingsGet200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getInvoiceSettingsWithHttpInfo($productType = null)
    {
        // parse inputs
        $resourcePath = "/invoicing/v2/invoiceSettings";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json', 'application/hal+json', 'application/json;charset=utf-8', 'application/hal+json;charset=utf-8']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json;charset=utf-8']);
        // query params
        if ($productType !== null) {
            $queryParams['productType'] = $this->apiClient->getSerializer()->toQueryValue($productType);
        }
        if ('GET' == 'POST') {
            $_tempBody = '{}';
        }
        // for model (json/xml)
        if (isset($_tempBody) and count($formParams) <= 0) {
            $httpBody = $_tempBody;
            // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = MultipartHelper::build_data_files($boundary, $formParams);
            // for HTTP post (form)
        }
        //MLE check and mle encryption for req body
        $inboundMLEStatus = 'false';
        if (MLEUtility::checkIsMLEForAPI($this->apiClient->merchantConfig, $inboundMLEStatus, "getInvoiceSettings,getInvoiceSettingsWithHttpInfo")) {
            try {
                $httpBody = MLEUtility::encryptRequestPayload($this->apiClient->merchantConfig, $httpBody);
            } catch (Exception $e) {
                self::$logger->error("Failed to encrypt request body:  {$e}");
                throw new ApiException("Failed to encrypt request body : " . $e->getMessage());
            }
        }
        // Logging
        self::$logger->debug("Resource : GET {$resourcePath}");
        self::$logger->debug("Query Parameters :\n" . \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ListHelper::toString($queryParams));
        if (isset($httpBody) and count($formParams) <= 0) {
            if ($this->apiClient->merchantConfig->getLogConfiguration()->isMaskingEnabled()) {
                $printHttpBody = \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\DataMasker::maskData($httpBody);
            } else {
                $printHttpBody = $httpBody;
            }
            self::$logger->debug("Body Parameter :\n" . $printHttpBody);
        }
        self::$logger->debug("Return Type : \\CyberSource\\Model\\InvoicingV2InvoiceSettingsGet200Response");
        // Response MLE check
        $isResponseMLEForAPI = MLEUtility::checkIsResponseMLEForAPI($this->apiClient->merchantConfig, "getInvoiceSettings,getInvoiceSettingsWithHttpInfo");
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi($resourcePath, 'GET', $queryParams, $httpBody, $headerParams, '\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoiceSettingsGet200Response', '/invoicing/v2/invoiceSettings', $isResponseMLEForAPI);
            self::$logger->debug("Response Headers :\n" . \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ListHelper::toString($httpHeader));
            return [$this->apiClient->getSerializer()->deserialize($response, '\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoiceSettingsGet200Response', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoiceSettingsGet200Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoicesAllGet400Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoicesAllGet502Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            self::$logger->error("ApiException : {$e}");
            throw $e;
        }
    }
    /**
     * Operation updateInvoiceSettings
     *
     * Update Invoice Settings
     *
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\InvoiceSettingsRequest $invoiceSettingsRequest  (required)
     * @param string $productType Allows you to choose which product type settings you want to update. (optional)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoiceSettingsGet200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateInvoiceSettings($invoiceSettingsRequest, $productType = null)
    {
        self::$logger->info('CALL TO METHOD updateInvoiceSettings STARTED');
        list($response, $statusCode, $httpHeader) = $this->updateInvoiceSettingsWithHttpInfo($invoiceSettingsRequest, $productType);
        self::$logger->info('CALL TO METHOD updateInvoiceSettings ENDED');
        self::$logger->close();
        return [$response, $statusCode, $httpHeader];
    }
    /**
     * Operation updateInvoiceSettingsWithHttpInfo
     *
     * Update Invoice Settings
     *
     * @param \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\InvoiceSettingsRequest $invoiceSettingsRequest  (required)
     * @param string $productType Allows you to choose which product type settings you want to update. (optional)
     * @throws \Pymt_Vas\Dependencies\CyberSource\ApiException on non-2xx response
     * @return array of \Pymt_Vas\Dependencies\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoiceSettingsGet200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateInvoiceSettingsWithHttpInfo($invoiceSettingsRequest, $productType = null)
    {
        // verify the required parameter 'invoiceSettingsRequest' is set
        if ($invoiceSettingsRequest === null) {
            self::$logger->error("InvalidArgumentException : Missing the required parameter {$invoiceSettingsRequest} when calling updateInvoiceSettings");
            throw new \InvalidArgumentException('Missing the required parameter $invoiceSettingsRequest when calling updateInvoiceSettings');
        }
        // parse inputs
        $resourcePath = "/invoicing/v2/invoiceSettings";
        $httpBody = '';
        $queryParams = [];
        $headerParams = [];
        $formParams = [];
        $_header_accept = $this->apiClient->selectHeaderAccept(['application/json', 'application/hal+json', 'application/json;charset=utf-8', 'application/hal+json;charset=utf-8']);
        if (!is_null($_header_accept)) {
            $headerParams['Accept'] = $_header_accept;
        }
        $headerParams['Content-Type'] = $this->apiClient->selectHeaderContentType(['application/json;charset=utf-8']);
        // query params
        if ($productType !== null) {
            $queryParams['productType'] = $this->apiClient->getSerializer()->toQueryValue($productType);
        }
        // body params
        $_tempBody = null;
        if (isset($invoiceSettingsRequest)) {
            $_tempBody = $invoiceSettingsRequest;
        }
        $sdkTracker = new \Pymt_Vas\Dependencies\CyberSource\Utilities\Tracking\SdkTracker();
        $modelClassLocation = explode('\\', '\Pymt_Vas\Dependencies\CyberSource\Model\InvoiceSettingsRequest');
        $_tempBody = $sdkTracker->insertDeveloperIdTracker($_tempBody, end($modelClassLocation), $this->apiClient->merchantConfig->getRunEnvironment(), $this->apiClient->merchantConfig->getDefaultDeveloperId());
        // for model (json/xml)
        if (isset($_tempBody) and count($formParams) <= 0) {
            $httpBody = $_tempBody;
            // $_tempBody is the method argument, if present
        } elseif (count($formParams) > 0) {
            $httpBody = MultipartHelper::build_data_files($boundary, $formParams);
            // for HTTP post (form)
        }
        //MLE check and mle encryption for req body
        $inboundMLEStatus = 'false';
        if (MLEUtility::checkIsMLEForAPI($this->apiClient->merchantConfig, $inboundMLEStatus, "updateInvoiceSettings,updateInvoiceSettingsWithHttpInfo")) {
            try {
                $httpBody = MLEUtility::encryptRequestPayload($this->apiClient->merchantConfig, $httpBody);
            } catch (Exception $e) {
                self::$logger->error("Failed to encrypt request body:  {$e}");
                throw new ApiException("Failed to encrypt request body : " . $e->getMessage());
            }
        }
        // Logging
        self::$logger->debug("Resource : PUT {$resourcePath}");
        self::$logger->debug("Query Parameters :\n" . \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ListHelper::toString($queryParams));
        if (isset($httpBody) and count($formParams) <= 0) {
            if ($this->apiClient->merchantConfig->getLogConfiguration()->isMaskingEnabled()) {
                $printHttpBody = \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\DataMasker::maskData($httpBody);
            } else {
                $printHttpBody = $httpBody;
            }
            self::$logger->debug("Body Parameter :\n" . $printHttpBody);
        }
        self::$logger->debug("Return Type : \\CyberSource\\Model\\InvoicingV2InvoiceSettingsGet200Response");
        // Response MLE check
        $isResponseMLEForAPI = MLEUtility::checkIsResponseMLEForAPI($this->apiClient->merchantConfig, "updateInvoiceSettings,updateInvoiceSettingsWithHttpInfo");
        // make the API Call
        try {
            list($response, $statusCode, $httpHeader) = $this->apiClient->callApi($resourcePath, 'PUT', $queryParams, $httpBody, $headerParams, '\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoiceSettingsGet200Response', '/invoicing/v2/invoiceSettings', $isResponseMLEForAPI);
            self::$logger->debug("Response Headers :\n" . \Pymt_Vas\Dependencies\CyberSource\Utilities\Helpers\ListHelper::toString($httpHeader));
            return [$this->apiClient->getSerializer()->deserialize($response, '\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoiceSettingsGet200Response', $httpHeader), $statusCode, $httpHeader];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoiceSettingsGet200Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoicesAllGet400Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = $this->apiClient->getSerializer()->deserialize($e->getResponseBody(), '\Pymt_Vas\Dependencies\CyberSource\Model\InvoicingV2InvoicesAllGet502Response', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    break;
            }
            self::$logger->error("ApiException : {$e}");
            throw $e;
        }
    }
}